name: Run Unit Tests
on: 
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js environment
        uses: actions/setup-node@v2.5.2
        
      - name: Install npm
        run: npm install

      - name: Run Tests
        run: npm run test:ci
